set( CPACK_PACKAGE_DESCRIPTION_SUMMARY "Not a very good description") # Not used by NSIS?

set( CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")
#set( CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_INSTALL_DIRECTORY}-${CPACK_SYSTEM_NAME}")
set( CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}")
set( CPACK_PACKAGE_INSTALL_REGISTRY_KEY "${CPACK_PACKAGE_NAME}${CPACK_PACKAGE_VERSION}" )

# if Generator is NSIS
set( CPACK_NSIS_PACKAGE_NAME ${CPACK_PACKAGE_INSTALL_DIRECTORY} )
set( CPACK_NSIS_DISPLAY_NAME ${CPACK_NSIS_PACKAGE_NAME} )

list( LENGTH CPACK_COMPONENTS_ALL list_length )
if( ${list_length} GREATER 1 )
foreach( loop_var IN LISTS CPACK_COMPONENTS_ALL )
  execute_process( COMMAND cpack -G NSIS -D CPACK_COMPONENTS_ALL=${loop_var} -P ${loop_var} )
endforeach()
endif()