set( CPACK_PACKAGE_DESCRIPTION_SUMMARY "Not a very good description") # Not used by NSIS?

set( CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")
set( CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_INSTALL_DIRECTORY}-${CPACK_SYSTEM_NAME}")
set( CPACK_PACKAGE_INSTALL_REGISTRY_KEY "${CPACK_PACKAGE_NAME}${CPACK_PACKAGE_VERSION}" )

set( CPACK_NSIS_PACKAGE_NAME ${CPACK_PACKAGE_INSTALL_DIRECTORY} )
set( CPACK_NSIS_DISPLAY_NAME ${CPACK_NSIS_PACKAGE_NAME} )