#set(CPACK_PACKAGE_NAME "Iosif_CPack_Example") #should you wish to override the above project setting
set(CPACK_PACKAGE_VENDOR "Iosif") 
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Not a very good description") # Not used by NSIS?
#set(CPACK_PACKAGE_VERSION "6.6.6") # major.minor.path
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")
set( CPACK_NSIS_PACKAGE_NAME ${CPACK_PACKAGE_INSTALL_DIRECTORY} )
set( CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_INSTALL_DIRECTORY}-${CPACK_SYSTEM_NAME}")